/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package xayn_kt_sdk.client

import org.junit.jupiter.api.assertThrows
import xayn_kt_sdk.client.model.PersonalizedDocumentsResponse
import java.lang.Exception
import kotlin.test.Test
import kotlin.test.assertTrue

class ClientTest {
    @Test
    fun likeDocumentTest() {
        val classUnderTest = Client(
            "{TOKEN}",
            "{ENDPOINT}",
            "{ENV}",
            "{USER}"
        )

        assertTrue(classUnderTest.likeDocument("test_a"), "likeDocument should return 'true'")
    }

    @Test
    fun personalizedDocumentsTest() {
        val classUnderTest = Client(
            "{TOKEN}",
            "{ENDPOINT}",
            "{ENV}",
            "{USER}"
        )

        assertTrue(classUnderTest.personalizedDocuments() is PersonalizedDocumentsResponse)
        assertThrows<Exception> { classUnderTest.personalizedDocuments(0) }
        assertThrows<Exception> { classUnderTest.personalizedDocuments(101) }
    }
}
